// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearClaudeDesktop():Promise<string>;

export function ClearClaudeDesktopApp():Promise<string>;

export function ClearSystemEnv():Promise<string>;

export function FetchQuota():Promise<Record<string, any>>;

export function FetchUpstreamModels():Promise<Record<string, any>>;

export function GetHubConfig():Promise<string>;

export function GetHubStatus():Promise<string>;

export function GetListenAddress():Promise<string>;

export function GetLocalToken():Promise<string>;

export function GetPreferences():Promise<Record<string, string>>;

export function HideToTray():Promise<void>;

export function InstallClaudeUserEnv():Promise<string>;

export function InstallVSCodeEnv():Promise<string>;

export function IsClaudeDesktopAppConfigured():Promise<boolean>;

export function IsClaudeDesktopConfigured():Promise<boolean>;

export function IsSystemEnvConfigured():Promise<boolean>;

export function IsVSCodeConfigured():Promise<boolean>;

export function LaunchClaudeTerminal(arg1:string,arg2:string):Promise<string>;

export function OpenConfigLocation():Promise<string>;

export function OpenLogLocation():Promise<string>;

export function QuitApp():Promise<void>;

export function RemoveVSCodeEnv():Promise<string>;

export function RepairAllConfigurations():Promise<string>;

export function SaveHubConfig(arg1:boolean,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function SaveLogPreferences(arg1:boolean,arg2:string,arg3:number):Promise<string>;

export function SavePreferences(arg1:string):Promise<string>;

export function SaveProfileConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:string):Promise<string>;

export function SaveUIPreferences(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SetupClaudeDesktop():Promise<string>;

export function SetupClaudeDesktopApp():Promise<string>;

export function ShowAboutDialog():Promise<void>;

export function SyncConfiguredIntegrations():Promise<string>;
