// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearClaudeDesktop() {
  return window['go']['main']['App']['ClearClaudeDesktop']();
}

export function GetListenAddress() {
  return window['go']['main']['App']['GetListenAddress']();
}

export function GetLocalToken() {
  return window['go']['main']['App']['GetLocalToken']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function InstallClaudeUserEnv() {
  return window['go']['main']['App']['InstallClaudeUserEnv']();
}

export function IsClaudeDesktopConfigured() {
  return window['go']['main']['App']['IsClaudeDesktopConfigured']();
}

export function LaunchClaudeTerminal(arg1, arg2) {
  return window['go']['main']['App']['LaunchClaudeTerminal'](arg1, arg2);
}

export function OpenConfigLocation() {
  return window['go']['main']['App']['OpenConfigLocation']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveProfileConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveProfileConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SetupClaudeDesktop() {
  return window['go']['main']['App']['SetupClaudeDesktop']();
}

export function ShowAboutDialog() {
  return window['go']['main']['App']['ShowAboutDialog']();
}
